language: go
go:
  - '1.11'

os:
  - linux
services: docker

env:
  ## Required external variables:
  ##   - DOCKER_USER, DOCKER_PASS
  ##   - GH_TOKEN, GH_KUBECONFIG_PATH
  global:
    - DEPLOYMENTS="rgv-api rgv-frontend"
    - RELEASE_BRANCH=master
    - DOCKER_COMPOSE_VERSION="1.23.2"

# Install external tools.
before_install:
  - export GOBIN="${GOPATH}/bin" BINPATH=/opt/bin
  - export PATH=$BINPATH:$PATH
  - ./scripts/tools.sh
  - git fetch --tags

## Install dependencies.
install: export GO111MODULE=on && make ci-install

## Run tests.
script: make ci-test

## Deploy to Docker Hub and Kubernetes.
deploy:
  provider: script
  script: ./scripts/deploy.sh
  skip-cleanup: true
  on:
    all_branches: true

## Upload code coverage results.
after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    ## Preserve external tools.
    - $BINPATH
    ## Preserve golint executable.
    - $GOBIN
    ## Preserve Go module cache.
    - ${GOPATH}/pkg/mod/cache
