{{- $name := include "api.name" . }}
{{- $fullName := include "api.fullname" . }}
{{- define "api-deploy-labels" }}
  {{- range $key, $val := .Values.deployments.api.labels }}
    {{- $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
{{- $labels := include "api-deploy-labels" . -}}

apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "chart.chart" . }}
{{ $labels | indent 4 }}

spec:
  replicas: {{ .Values.deployments.api.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{ $labels | indent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
{{ $labels | indent 8 }}
    spec:
      containers:
        - name: {{ $name }}
          image: {{ .Values.deployments.api.image | quote }}
          imagePullPolicy: {{ .Values.deployments.api.imagePullPolicy }}
          ports:
            - name: api
              containerPort: 3000
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: api
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: api
          # {{- with .Values.deployments.api.resources }}
          resources:
            {{ toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.deployments.api.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployments.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 -}}
      {{- end }}
      {{- with .Values.deployments.api.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
