---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: rgv-api
  namespace: default

spec:
  replicas: 1
  selector:
    matchLabels:
      app: rgv-api
      tier: backend
      track: stable
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: rgv-api
        tier: backend
        track: stable
    spec:
      containers:
        - name: rgv-api
          image: "stevenxie/rgv.api"
          imagePullPolicy: Always
          volumeMounts:
            - name: env
              mountPath: "/secrets/env"
          ports:
            - name: api
              containerPort: 3000
      volumes:
        - name: env
          secret:
            secretName: rgv-api-env
            defaultMode: 256

