{{- $name := include "rgv.name" . -}}
{{- $service := .Values.api.service -}}

apiVersion: v1
kind: Service

metadata:
  name: {{ include "rgv.fullname" . }}-api
  labels:
    app.kubernetes.io/name: {{ $name }}-api
    helm.sh/chart: {{ include "rgv.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with $service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}


spec:
  type: {{ $service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ $service.port }}
  selector:
    app.kubernetes.io/name: {{ $name }}-api
    app.kubernetes.io/instance: {{ .Release.Name }}
